set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_C_COMPILER $ENV{CROSS_COMPILER}/bin/i686-elf-gcc)
set(CMAKE_ASM-ATT_COMPILER $ENV{CROSS_COMPILER}/bin/i686-elf-as)
set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")